import React, { useState, useEffect, useRef } from 'react';
import { UrlAnalyzer } from './UrlAnalyzer';
import { motion, AnimatePresence } from 'motion/react';
import {
  Search, Sparkles, Brain, ScanLine, FileText, CheckCircle2,
  ChevronDown, HelpCircle, Shield, AlertTriangle, Zap, Eye,
  ArrowRight, TrendingUp, Star, Lock, Globe, Activity
} from 'lucide-react';

interface LandingPageProps {
  onStartAnalysis: () => void;
  onViewProducts?: () => void;
}

// Scroll reveal hook
function useScrollReveal() {
  const ref = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setIsVisible(true); },
      { threshold: 0.12, rootMargin: '0px 0px -40px 0px' }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return { ref, isVisible };
}

// Animated counter hook
function useCounter(target: number, duration: number = 1800, isVisible: boolean = false) {
  const [count, setCount] = useState(0);
  useEffect(() => {
    if (!isVisible) return;
    let start = 0;
    const step = target / (duration / 16);
    const timer = setInterval(() => {
      start += step;
      if (start >= target) { setCount(target); clearInterval(timer); }
      else setCount(Math.floor(start));
    }, 16);
    return () => clearInterval(timer);
  }, [isVisible, target, duration]);
  return count;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onViewProducts }) => {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [sampleUrl, setSampleUrl] = useState<string>('');
  const howItWorks = useScrollReveal();
  const bentoSection = useScrollReveal();
  const faqSection = useScrollReveal();
  const statsSection = useScrollReveal();

  const scansCount = useCounter(2340000, 2000, statsSection.isVisible);
  const accuracyCount = useCounter(994, 1600, statsSection.isVisible);
  const platformsCount = useCounter(8, 800, statsSection.isVisible);
  const brandsCount = useCounter(1200, 1400, statsSection.isVisible);

  const faqs = [
    { q: "How accurate is the authenticity check?", a: "Our advanced system achieves 99.4% accuracy by cross-referencing micro-stitching, hardware finishes, and typography against an extensive database of verified authentic luxury goods. It also performs deep NLP analysis on customer reviews." },
    { q: "Which platforms do you support?", a: "VeriStyle currently supports Amazon, Flipkart, Myntra, Nykaa, and AJIO. You can paste links from any of these platforms for instant verification." },
    { q: "What is a 'Fake Review'?", a: "A Fake Review is text generated by bots or paid resellers to artificially inflate ratings. Our AI detects repetitive linguistic patterns, unnatural language, and sentiment mismatches to flag them." },
    { q: "Can I use VeriStyle for sneakers and streetwear?", a: "Yes, our image scanner is trained on luxury handbags, limited-edition sneakers, designer streetwear, and high-end watches with over 1,200+ brand templates." },
    { q: "Is my data secure?", a: "All uploads are processed in-memory and never stored. Verification hashes are cryptographically signed for provenance tracking but contain no personally identifiable information." },
  ];

  const stores = [
    { name: 'Amazon', domain: 'amazon.in' },
    { name: 'Flipkart', domain: 'flipkart.com' },
    { name: 'Myntra', domain: 'myntra.com' },
    { name: 'AJIO', domain: 'ajio.com' },
    { name: 'Nykaa', domain: 'nykaa.com' },
    { name: 'Croma', domain: 'croma.com' },
    { name: 'Meesho', domain: 'meesho.com' },
    { name: 'Tata CLiQ', domain: 'tatacliq.com' },
  ];

  return (
    <div className="w-full flex flex-col min-h-screen" style={{ background: 'var(--bg-base)' }}>

      {/* ═══ 1. HERO SECTION — Premium warm gradient with multi-color orbs ═══ */}
      <section
        className="relative w-full flex flex-col items-center justify-center overflow-hidden px-4 pt-[140px] sm:pt-[180px] lg:pt-[196px] pb-20 sm:pb-28"
        style={{ background: 'linear-gradient(180deg, #F8F6F1 0%, #F5F3EE 30%, #F2EFE8 60%, #FAFAF8 100%)' }}
      >
        {/* Ambient morphing orbs */}
        <div
          className="absolute top-[5%] left-[5%] w-[500px] h-[500px] ambient-orb ambient-orb-green animate-morph"
          style={{ animationDelay: '0s' }}
        />
        <div
          className="absolute top-[15%] right-[8%] w-[400px] h-[400px] ambient-orb ambient-orb-indigo animate-morph"
          style={{ animationDelay: '3s' }}
        />
        <div
          className="absolute bottom-[10%] left-[20%] w-[350px] h-[350px] ambient-orb ambient-orb-gold animate-morph"
          style={{ animationDelay: '5s' }}
        />
        <div
          className="absolute bottom-[5%] right-[15%] w-[300px] h-[300px] ambient-orb ambient-orb-rose animate-morph"
          style={{ animationDelay: '7s' }}
        />

        {/* Dot grid overlay */}
        <div className="absolute inset-0 dot-grid-bg opacity-60 pointer-events-none" />

        {/* Prismatic scanline */}
        <div className="absolute inset-0 pointer-events-none overflow-hidden">
          <div
            className="absolute left-0 right-0 h-[1px] animate-scanline-v"
            style={{ background: 'linear-gradient(90deg, transparent, rgba(52,216,138,0.15), rgba(129,140,248,0.12), rgba(251,191,36,0.08), transparent)' }}
          />
        </div>

        <div className="relative z-10 w-full max-w-6xl mx-auto px-2 sm:px-6 text-center flex flex-col items-center">

          {/* Badge — multi-tone */}
          <motion.div
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-8"
            style={{
              background: 'linear-gradient(135deg, rgba(52,216,138,0.06), rgba(129,140,248,0.04))',
              border: '1px solid rgba(52,216,138,0.15)',
              backdropFilter: 'blur(8px)',
            }}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            <Sparkles className="w-3.5 h-3.5" style={{ color: 'var(--green-primary)' }} />
            <span className="text-xs font-bold uppercase tracking-widest" style={{ color: 'var(--green-primary)' }}>
              Multimodal AI Fashion Verification
            </span>
          </motion.div>

          {/* Main Headline — multi-color gradient */}
          <motion.h1
            className="text-[40px] leading-[1.05] sm:text-[58px] md:text-[72px] font-extrabold tracking-tight mb-6"
            style={{ fontFamily: 'var(--font-heading)', color: 'var(--text-primary)' }}
            initial={{ opacity: 0, y: 28 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
          >
            Verify With Absolute
            <br />
            <motion.span
              className="italic"
              style={{
                fontFamily: 'var(--font-serif)',
                background: 'linear-gradient(135deg, #34D88A 0%, #00B864 30%, #818CF8 70%, #A78BFA 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
              initial={{ opacity: 0, scale: 0.92 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.9, delay: 0.45, ease: [0.16, 1, 0.3, 1] }}
            >
              Confidence.
            </motion.span>
          </motion.h1>

          {/* Sub-headline */}
          <motion.p
            className="text-[16px] sm:text-[20px] max-w-2xl mb-12 leading-relaxed"
            style={{ color: 'var(--text-muted)' }}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
          >
            Paste any fashion product link for instant AI authenticity analysis.
            Powered by computer vision and natural language forensics.
          </motion.p>

          {/* URL Analyzer — terminal style wrapper */}
          <motion.div
            className="w-full mb-6"
            initial={{ opacity: 0, y: 20, scale: 0.97 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            transition={{ duration: 0.8, delay: 0.55, ease: [0.16, 1, 0.3, 1] }}
          >
            <div className="animate-focus-glow rounded-2xl">
              <UrlAnalyzer standalone={false} initialUrl={sampleUrl} />
            </div>
          </motion.div>

          {/* Try chips */}
          <motion.div
            className="flex flex-wrap items-center justify-center gap-2 text-sm"
            style={{ color: 'var(--text-muted)' }}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.9 }}
          >
            <span className="font-medium text-xs">Try:</span>
            {[
              { label: 'amazon.in/nike-jordan', url: 'https://www.amazon.in/Nike-Air-Jordan-Retro-Sneakers/dp/B0CKW79YQ4' },
              { label: 'flipkart.com/gucci-bag', url: 'https://www.flipkart.com/gucci-leather-handbag-dionysus/p/itm2894721' },
              { label: 'myntra.com/yeezy', url: 'https://www.myntra.com/casual-shoes/adidas/yeezy-boost-350-v2-sneakers/19482910/buy' }
            ].map((item, i) => (
              <motion.button
                key={item.label}
                onClick={() => setSampleUrl(item.url)}
                className="px-3 py-1 rounded-full text-xs font-medium cursor-pointer transition-all"
                style={{
                  background: 'rgba(255,255,255,0.7)',
                  border: '1px solid rgba(0,0,0,0.06)',
                  color: 'var(--text-muted)',
                  fontFamily: 'var(--font-mono)',
                  boxShadow: '0 1px 4px rgba(0,0,0,0.02)',
                }}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.95 + i * 0.08 }}
                whileHover={{
                  scale: 1.05,
                  background: 'rgba(52,216,138,0.08)',
                  borderColor: 'rgba(52,216,138,0.3)',
                  color: 'var(--green-primary)',
                }}
                whileTap={{ scale: 0.95 }}
              >
                {item.label}
              </motion.button>
            ))}
          </motion.div>

          {/* Hero stat pills — glass morphism */}
          <motion.div
            className="flex flex-wrap items-center justify-center gap-3 mt-10"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 1.1 }}
          >
            {[
              { label: '99.4% Accuracy', icon: TrendingUp, color: '#34D88A' },
              { label: '2.3M+ Scans', icon: Activity, color: '#818CF8' },
              { label: '8 Platforms', icon: Globe, color: '#FBBF24' },
              { label: '1,200+ Brands', icon: Star, color: '#FB7185' },
            ].map(({ label, icon: Icon, color }) => (
              <motion.div
                key={label}
                className="flex items-center gap-1.5 px-3.5 py-2 rounded-full text-xs font-semibold"
                style={{
                  background: 'rgba(255,255,255,0.75)',
                  border: '1px solid rgba(0,0,0,0.05)',
                  color: 'var(--text-secondary)',
                  boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
                  backdropFilter: 'blur(12px)',
                }}
                whileHover={{ scale: 1.05, y: -2 }}
                transition={{ type: 'spring', stiffness: 400, damping: 20 }}
              >
                <Icon className="w-3.5 h-3.5" style={{ color }} />
                {label}
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ═══ 2. STATS COUNTERS — DARK CONTRAST SECTION ═══ */}
      <section
        ref={statsSection.ref}
        className="w-full py-20 px-4 relative overflow-hidden dark-section"
      >
        {/* Ambient orbs on dark */}
        <div className="absolute top-[-20%] left-[-10%] w-[400px] h-[400px] rounded-full blur-3xl pointer-events-none" style={{ background: 'rgba(52,216,138,0.06)' }} />
        <div className="absolute bottom-[-20%] right-[-10%] w-[350px] h-[350px] rounded-full blur-3xl pointer-events-none" style={{ background: 'rgba(129,140,248,0.05)' }} />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[300px] rounded-full blur-3xl pointer-events-none" style={{ background: 'rgba(245,200,66,0.03)' }} />

        <div className="max-w-5xl mx-auto grid grid-cols-2 lg:grid-cols-4 gap-8 relative z-10">
          {[
            { value: scansCount, suffix: '+', label: 'Total Scans', prefix: '', color: '#34D88A' },
            { value: accuracyCount / 10, suffix: '%', label: 'Accuracy Rate', prefix: '', color: '#818CF8' },
            { value: platformsCount, suffix: '', label: 'Supported Platforms', prefix: '', color: '#FBBF24' },
            { value: brandsCount, suffix: '+', label: 'Brand Templates', prefix: '', color: '#FB7185' },
          ].map(({ value, suffix, label, prefix, color }, i) => (
            <motion.div
              key={label}
              className="text-center"
              initial={{ opacity: 0, y: 16 }}
              animate={statsSection.isVisible ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: i * 0.1 }}
            >
              <div
                className="text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight mb-2"
                style={{
                  fontFamily: 'var(--font-heading)',
                  color,
                  textShadow: `0 0 30px ${color}33`,
                }}
              >
                {prefix}{i === 0 ? (value >= 1000000 ? `${(value / 1000000).toFixed(1)}M` : value.toLocaleString()) : value.toFixed(i === 1 ? 1 : 0)}{suffix}
              </div>
              <div className="text-xs font-semibold uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.5)' }}>{label}</div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ═══ 3. STORES MARQUEE — on light ═══ */}
      <section className="w-full py-10 overflow-hidden" style={{ background: 'var(--bg-base)', borderBottom: '1px solid rgba(0,0,0,0.04)' }}>
        <div
          className="animate-marquee flex items-center gap-14 w-max"
          style={{ opacity: 0.45 }}
        >
          {[...stores, ...stores].map((store, i) => (
            <div key={`${store.name}-${i}`} className="flex items-center gap-2.5 font-bold text-lg shrink-0" style={{ color: 'var(--text-secondary)' }}>
              <img
                src={`https://icon.horse/icon/${store.domain}`}
                alt={store.name}
                className="w-7 h-7 rounded-lg object-contain"
                style={{ opacity: 0.6 }}
              />
              {store.name}
            </div>
          ))}
        </div>
      </section>

      {/* ═══ 4. HOW IT WORKS — Premium cards with color accents ═══ */}
      <section
        className="w-full py-24 sm:py-32 px-4 sm:px-6 lg:px-8"
        id="how-it-works"
        ref={howItWorks.ref}
        style={{ background: 'var(--bg-base)' }}
      >
        <div className="max-w-7xl mx-auto space-y-16">
          <div className="text-center">
            <div className="section-badge mx-auto mb-5">
              <Zap className="w-3 h-3" />
              How It Works
            </div>
            <h2
              className="text-[32px] sm:text-[46px] font-bold tracking-tight mb-4"
              style={{ fontFamily: 'var(--font-heading)', color: 'var(--text-primary)' }}
            >
              Four Steps to <span className="italic" style={{ fontFamily: 'var(--font-serif)', background: 'linear-gradient(135deg, #34D88A, #00B864)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>Certainty.</span>
            </h2>
            <p className="text-lg max-w-2xl mx-auto" style={{ color: 'var(--text-muted)' }}>
              Combining visual inspection with NLP review analysis for unmatched authenticity scoring.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 relative">
            {/* Connecting line — gradient */}
            <div
              className="hidden lg:block absolute top-16 left-[12%] right-[12%] h-px z-0"
              style={{ background: 'linear-gradient(90deg, #34D88A33, #818CF833, #FBBF2433, #FB718533)' }}
            />

            {[
              { step: 1, title: 'Find Product', desc: 'Copy the URL of any fashion item from our 8 supported stores.', icon: Search, color: '#34D88A', glowColor: 'rgba(52,216,138,0.08)' },
              { step: 2, title: 'Paste URL', desc: "Paste the link into VeriStyle's AI analyzer bar above.", icon: ScanLine, color: '#818CF8', glowColor: 'rgba(129,140,248,0.08)' },
              { step: 3, title: 'Data Extraction', desc: 'We fetch images, price history, and reviews in real-time.', icon: Brain, color: '#FBBF24', glowColor: 'rgba(251,191,36,0.08)' },
              { step: 4, title: 'Get Verdict', desc: 'Receive an instant authenticity score with detailed breakdown.', icon: CheckCircle2, color: '#FB7185', glowColor: 'rgba(251,113,133,0.08)' },
            ].map((item, idx) => (
              <motion.div
                key={idx}
                className="relative z-10 neon-card p-7 flex flex-col card-shine"
                initial={{ opacity: 0, y: 28 }}
                animate={howItWorks.isVisible ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.6, delay: idx * 0.12, ease: [0.16, 1, 0.3, 1] }}
              >
                {/* Step number */}
                <div className="text-[11px] font-black uppercase tracking-widest mb-4 font-mono" style={{ color: 'var(--text-dim)' }}>
                  Step 0{item.step}
                </div>
                <div
                  className="w-12 h-12 rounded-xl flex items-center justify-center mb-5"
                  style={{
                    background: item.glowColor,
                    border: `1px solid ${item.color}20`,
                    boxShadow: `0 4px 16px ${item.color}10`,
                  }}
                >
                  <item.icon className="w-6 h-6" style={{ color: item.color }} />
                </div>
                <h3 className="text-[18px] font-bold mb-2.5" style={{ fontFamily: 'var(--font-heading)', color: 'var(--text-primary)' }}>{item.title}</h3>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>{item.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ 5. BENTO FEATURES GRID — Premium multi-color ═══ */}
      <section
        className="w-full py-24 sm:py-32 px-4 sm:px-6 lg:px-8"
        ref={bentoSection.ref}
        style={{ background: 'var(--bg-surface-1)', borderTop: '1px solid rgba(0,0,0,0.04)' }}
      >
        <div className="max-w-7xl mx-auto space-y-14">
          <div className="text-center max-w-3xl mx-auto">
            <div className="section-badge mx-auto mb-5">
              <Sparkles className="w-3 h-3" />
              Dual-Engine Intelligence
            </div>
            <h2
              className="text-[32px] sm:text-[46px] font-extrabold tracking-tight"
              style={{ fontFamily: 'var(--font-heading)', color: 'var(--text-primary)' }}
            >
              Image & Review{' '}
              <span
                className="italic"
                style={{ fontFamily: 'var(--font-serif)', background: 'linear-gradient(135deg, #34D88A, #818CF8)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}
              >
                Forensics.
              </span>
            </h2>
            <p className="mt-4 text-base sm:text-lg" style={{ color: 'var(--text-muted)' }}>
              Combining visual micro-inspection of hardware and stitching with NLP text entropy analysis for unparalleled accuracy.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">

            {/* Card 1: NLP Intelligence — large indigo accent */}
            <motion.div
              className="lg:col-span-2 p-8 sm:p-10 rounded-2xl flex flex-col justify-between relative overflow-hidden card-shine"
              style={{
                background: 'linear-gradient(135deg, rgba(129,140,248,0.04) 0%, #FFFFFF 60%)',
                border: '1px solid rgba(129,140,248,0.10)',
                boxShadow: 'var(--card-shadow)',
              }}
              initial={{ opacity: 0, y: 24 }}
              animate={bentoSection.isVisible ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.1 }}
            >
              <div className="absolute top-0 right-0 w-48 h-48 rounded-full blur-3xl pointer-events-none" style={{ background: 'rgba(129,140,248,0.05)' }} />
              <div className="absolute bottom-0 left-0 w-32 h-32 rounded-full blur-3xl pointer-events-none" style={{ background: 'rgba(167,139,250,0.04)' }} />
              <div>
                <div
                  className="w-11 h-11 rounded-xl flex items-center justify-center mb-5"
                  style={{ background: 'rgba(129,140,248,0.08)', border: '1px solid rgba(129,140,248,0.14)' }}
                >
                  <FileText className="w-5 h-5" style={{ color: '#818CF8' }} />
                </div>
                <div className="mono-label mb-3" style={{ color: '#818CF8' }}>Natural Language Forensics</div>
                <h3
                  className="text-2xl sm:text-3xl font-extrabold mb-4 tracking-tight"
                  style={{ fontFamily: 'var(--font-heading)', color: 'var(--text-primary)' }}
                >
                  Deconstructing Fake & Paid Reviews
                </h3>
                <p className="text-base leading-relaxed max-w-xl" style={{ color: 'var(--text-muted)' }}>
                  Our system inspects thousands of customer reviews, isolating suspicious keyword repetition, artificial sentiment clusters, and paid bot activity to deliver true buyer consensus.
                </p>
              </div>
              <div className="mt-8 pt-6 flex flex-wrap items-center gap-5 text-xs font-bold" style={{ borderTop: '1px solid rgba(129,140,248,0.08)', color: '#818CF8' }}>
                <span className="flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4" /> Perplexity Entropy Scoring</span>
                <span className="flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4" /> Sentiment-Rating Coherence</span>
                <span className="flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4" /> Bot Syndicate Detection</span>
              </div>
            </motion.div>

            {/* Card 2: Confidence Score — green glow */}
            <motion.div
              className="rounded-2xl p-8 flex flex-col items-center justify-center text-center relative overflow-hidden"
              style={{
                background: 'linear-gradient(135deg, #ECFDF5 0%, #D1FAE5 100%)',
                border: '1px solid rgba(52,216,138,0.15)',
                boxShadow: '0 4px 24px rgba(0,0,0,0.04)',
              }}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={bentoSection.isVisible ? { opacity: 1, scale: 1 } : {}}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              <div className="absolute top-0 right-0 w-32 h-32 rounded-full blur-2xl pointer-events-none animate-breathe" style={{ background: 'rgba(52,216,138,0.08)' }} />
              <div
                className="w-14 h-14 rounded-2xl flex items-center justify-center mb-4 animate-glow-pulse"
                style={{ background: 'rgba(52,216,138,0.08)', border: '1px solid rgba(52,216,138,0.18)' }}
              >
                <Shield className="w-7 h-7" style={{ color: '#34D88A' }} />
              </div>
              <div className="mono-label mb-2">Real-Time Metric</div>
              <h3 className="text-xl font-bold mb-3" style={{ fontFamily: 'var(--font-heading)', color: 'var(--text-primary)' }}>Confidence Score</h3>
              <div
                className="text-6xl sm:text-7xl font-black my-4 font-mono"
                style={{
                  background: 'linear-gradient(135deg, #34D88A, #00B864)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  backgroundClip: 'text',
                }}
              >
                98.4%
              </div>
              <div className="px-4 py-1.5 rounded-full text-xs font-black uppercase tracking-wider" style={{ background: 'rgba(52,216,138,0.10)', border: '1px solid rgba(52,216,138,0.20)', color: '#00B864' }}>
                Verified Authentic
              </div>
            </motion.div>

            {/* Card 3: Bot Shield — amber accent */}
            <motion.div
              className="rounded-2xl p-8 relative overflow-hidden card-shine"
              style={{
                background: 'linear-gradient(135deg, rgba(251,191,36,0.04) 0%, #FFFFFF 60%)',
                border: '1px solid rgba(251,191,36,0.10)',
              }}
              initial={{ opacity: 0, y: 24 }}
              animate={bentoSection.isVisible ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.3 }}
            >
              <div
                className="w-11 h-11 rounded-xl flex items-center justify-center mb-4"
                style={{ background: 'rgba(251,191,36,0.08)', border: '1px solid rgba(251,191,36,0.14)' }}
              >
                <AlertTriangle className="w-5 h-5" style={{ color: '#FBBF24' }} />
              </div>
              <div className="mono-label mb-2" style={{ color: '#D97706' }}>Bot Shield</div>
              <h3 className="text-xl font-bold mb-2" style={{ fontFamily: 'var(--font-heading)', color: 'var(--text-primary)' }}>Review Spam Detection</h3>
              <p className="text-sm mb-6 leading-relaxed" style={{ color: 'var(--text-muted)' }}>
                Flags sponsored syndicates and deceptive 5-star blitzes in real time.
              </p>
              <div className="space-y-3 p-4 rounded-xl" style={{ background: 'rgba(251,191,36,0.04)', border: '1px solid rgba(251,191,36,0.08)' }}>
                <div className="flex justify-between text-xs font-bold" style={{ color: '#D97706' }}>
                  <span>Organic Vocabulary Rate</span>
                  <span>94.8%</span>
                </div>
                <div className="metric-track">
                  <motion.div
                    className="h-full rounded-full"
                    style={{ background: 'linear-gradient(90deg, #D97706, #FBBF24)', boxShadow: '0 0 8px rgba(251,191,36,0.30)' }}
                    initial={{ width: 0 }}
                    animate={bentoSection.isVisible ? { width: '94.8%' } : { width: 0 }}
                    transition={{ duration: 1.3, delay: 0.5, ease: [0.16, 1, 0.3, 1] }}
                  />
                </div>
              </div>
            </motion.div>

            {/* Card 4: Computer Vision — sky accent, large */}
            <motion.div
              className="lg:col-span-2 p-8 sm:p-10 rounded-2xl relative overflow-hidden card-shine"
              style={{
                background: 'linear-gradient(135deg, rgba(56,189,248,0.04) 0%, #FFFFFF 60%)',
                border: '1px solid rgba(56,189,248,0.10)',
              }}
              initial={{ opacity: 0, y: 24 }}
              animate={bentoSection.isVisible ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.4 }}
            >
              <div className="absolute top-0 right-0 w-36 h-36 rounded-full blur-3xl pointer-events-none" style={{ background: 'rgba(56,189,248,0.05)' }} />
              <div className="flex items-center gap-3 mb-6">
                <div
                  className="w-11 h-11 rounded-xl flex items-center justify-center"
                  style={{ background: 'rgba(56,189,248,0.08)', border: '1px solid rgba(56,189,248,0.14)' }}
                >
                  <ScanLine className="w-5 h-5" style={{ color: '#38BDF8' }} />
                </div>
                <div>
                  <div className="mono-label" style={{ color: '#38BDF8' }}>Computer Vision Forensics</div>
                  <h3 className="text-xl sm:text-2xl font-extrabold tracking-tight" style={{ fontFamily: 'var(--font-heading)', color: 'var(--text-primary)' }}>
                    Micro-Stitching & Material Analysis
                  </h3>
                </div>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {[
                  { title: 'Thread Pitch & Gauge', desc: 'Cross-referenced against verified manufacturer seam patterns and tension parameters.' },
                  { title: 'Electroplating & Debossing', desc: 'Reflective gloss and font depth inspected for exact authentic stamping fidelity.' },
                  { title: 'Fabric Texture Match', desc: 'HSV color profiles and weave patterns matched against master textile databases.' },
                  { title: 'Serial Code Validation', desc: 'Serial number formatting cross-checked against brand registries in real-time.' },
                ].map(({ title, desc }) => (
                  <div key={title} className="p-4 rounded-xl transition-all duration-300 hover:translate-y-[-2px]" style={{ background: 'rgba(56,189,248,0.03)', border: '1px solid rgba(56,189,248,0.07)' }}>
                    <p className="text-xs font-bold uppercase tracking-wider mb-1.5" style={{ color: '#38BDF8' }}>{title}</p>
                    <p className="text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>{desc}</p>
                  </div>
                ))}
              </div>
            </motion.div>

          </div>
        </div>
      </section>

      {/* ═══ 6. FAQ — DARK SECTION for contrast ═══ */}
      <section
        className="w-full py-24 sm:py-32 px-4 relative overflow-hidden dark-section"
        id="faq"
        ref={faqSection.ref}
      >
        {/* Dark ambient orbs */}
        <div className="absolute top-[10%] right-[10%] w-[400px] h-[400px] rounded-full blur-3xl pointer-events-none animate-morph" style={{ background: 'rgba(52,216,138,0.04)', animationDelay: '2s' }} />
        <div className="absolute bottom-[10%] left-[5%] w-[350px] h-[350px] rounded-full blur-3xl pointer-events-none animate-morph" style={{ background: 'rgba(129,140,248,0.04)', animationDelay: '4s' }} />

        <div className="max-w-3xl mx-auto space-y-12 relative z-10">
          <motion.div
            className="text-center flex flex-col items-center"
            initial={{ opacity: 0, y: 20 }}
            animate={faqSection.isVisible ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6 }}
          >
            <div
              className="w-12 h-12 rounded-2xl flex items-center justify-center mb-5"
              style={{ background: 'rgba(52,216,138,0.08)', border: '1px solid rgba(52,216,138,0.15)' }}
            >
              <HelpCircle className="w-6 h-6" style={{ color: '#34D88A' }} />
            </div>
            <h2
              className="text-[32px] sm:text-[44px] font-extrabold tracking-tight"
              style={{ fontFamily: 'var(--font-heading)', color: '#F1F5F9' }}
            >
              Frequently Asked{' '}
              <span
                className="italic"
                style={{ fontFamily: 'var(--font-serif)', background: 'linear-gradient(135deg, #34D88A, #6EE7B7)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}
              >
                Questions.
              </span>
            </h2>
            <p className="text-sm sm:text-base mt-3" style={{ color: 'rgba(255,255,255,0.5)' }}>
              Everything you need to know about our multimodal authenticity verification.
            </p>
          </motion.div>

          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <motion.div
                key={i}
                className="rounded-2xl overflow-hidden"
                style={{
                  background: openFaq === i ? 'rgba(255,255,255,0.06)' : 'rgba(255,255,255,0.03)',
                  border: openFaq === i ? '1px solid rgba(52,216,138,0.15)' : '1px solid rgba(255,255,255,0.06)',
                  backdropFilter: 'blur(12px)',
                  transition: 'all 0.3s ease',
                }}
                initial={{ opacity: 0, y: 16 }}
                animate={faqSection.isVisible ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.5, delay: i * 0.08 }}
              >
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full px-6 py-5 text-left flex justify-between items-center transition-colors cursor-pointer"
                >
                  <span className="font-bold text-[15px] pr-4" style={{ fontFamily: 'var(--font-heading)', color: openFaq === i ? '#34D88A' : 'rgba(255,255,255,0.7)' }}>
                    {faq.q}
                  </span>
                  <motion.div
                    animate={{ rotate: openFaq === i ? 180 : 0 }}
                    transition={{ duration: 0.3 }}
                  >
                    <ChevronDown className="w-5 h-5 shrink-0" style={{ color: '#34D88A' }} />
                  </motion.div>
                </button>
                <AnimatePresence initial={false}>
                  {openFaq === i && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
                      className="overflow-hidden"
                    >
                      <div
                        className="px-6 pb-6 pt-2 text-sm leading-relaxed mx-6 mt-2 mb-3 rounded-xl"
                        style={{
                          color: 'rgba(255,255,255,0.5)',
                          borderTop: '1px solid rgba(255,255,255,0.06)',
                        }}
                      >
                        <div className="pt-4">{faq.a}</div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ 7. BOTTOM CTA BANNER — warm light with premium gradient ═══ */}
      <section
        className="w-full py-24 px-4 text-center relative overflow-hidden"
        style={{ background: 'linear-gradient(180deg, var(--bg-surface-1), var(--bg-base))' }}
      >
        {/* Ambient premium orbs */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[500px] h-[250px] rounded-full blur-3xl pointer-events-none" style={{ background: 'rgba(52,216,138,0.05)' }} />
        <div className="absolute bottom-0 left-[10%] w-[300px] h-[300px] rounded-full blur-3xl pointer-events-none animate-morph" style={{ background: 'rgba(129,140,248,0.04)' }} />
        <div className="absolute bottom-0 right-[10%] w-[250px] h-[250px] rounded-full blur-3xl pointer-events-none animate-morph" style={{ background: 'rgba(251,191,36,0.04)', animationDelay: '3s' }} />

        <div className="absolute inset-0 dot-grid-bg opacity-30 pointer-events-none" />
        <div className="relative z-10 max-w-2xl mx-auto">
          <div className="section-badge mx-auto mb-6">
            <Lock className="w-3 h-3" />
            Zero Data Stored
          </div>
          <h2
            className="text-[28px] sm:text-[40px] font-extrabold tracking-tight mb-4"
            style={{ fontFamily: 'var(--font-heading)', color: 'var(--text-primary)' }}
          >
            Start Verifying Instantly.
            <br />
            <span
              className="italic"
              style={{ fontFamily: 'var(--font-serif)', background: 'linear-gradient(135deg, #34D88A, #818CF8)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}
            >
              No signup required.
            </span>
          </h2>
          <p className="text-base mb-10" style={{ color: 'var(--text-muted)' }}>
            Paste any product link or upload an image to get your detailed forensic analysis report in seconds.
          </p>
          <motion.button
            onClick={onViewProducts}
            className="inline-flex items-center gap-2.5 px-8 py-4 rounded-2xl text-base font-bold cursor-pointer btn-neon"
            whileHover={{ scale: 1.04, y: -2 }}
            whileTap={{ scale: 0.97 }}
          >
            <Eye className="w-5 h-5" />
            Explore Verified Products
            <ArrowRight className="w-5 h-5" />
          </motion.button>
        </div>
      </section>

    </div>
  );
};
