import React, { useState } from 'react';
import { UrlAnalyzer } from './UrlAnalyzer';
import { PRODUCTS } from '../data/products';
import { Search, Sparkles, Brain, ScanLine, FileText, CheckCircle2, ChevronDown, HelpCircle, Shield, AlertTriangle } from 'lucide-react';
import { ProductCard } from './ProductCard';

interface LandingPageProps {
  onStartAnalysis: () => void;
  onViewProducts?: () => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onViewProducts }) => {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const faqs = [
    { q: "How accurate is the AI authenticity analysis?", a: "Our multimodal AI model achieves 99.4% accuracy by cross-referencing micro-stitching, hardware finishes, and typography against an extensive database of verified authentic luxury goods. It also performs NLP perplexity checks on reviews." },
    { q: "Which platforms do you support?", a: "VeriStyle currently supports Amazon, Flipkart, Myntra, Nykaa, and AJIO. You can paste links from any of these platforms for instant verification." },
    { q: "What is a 'Synthetic Review'?", a: "A synthetic review is text generated by bots or paid resellers to artificially inflate ratings. Our AI detects repetitive linguistic patterns, unnatural entropy, and sentiment mismatches to flag them." },
    { q: "Can I use VeriStyle for sneakers and streetwear?", a: "Yes, our vision engine is trained on luxury handbags, limited-edition sneakers, designer streetwear, and high-end watches." }
  ];

  return (
    <div className="w-full flex flex-col min-h-screen pt-[72px] sm:pt-[82px] lg:pt-[93px]">
      
      {/* 1. Hero Section */}
      <section 
        className="relative w-full flex flex-col items-center justify-center overflow-hidden px-4 py-16 sm:py-24"
        style={{ background: 'var(--hero-bg)' }}
      >
        {/* SVG Grid Overlay */}
        <div className="absolute inset-0 opacity-20 pointer-events-none" style={{ backgroundImage: 'url("data:image/svg+xml,%3Csvg width=\'40\' height=\'40\' viewBox=\'0 0 40 40\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cpath d=\'M0 0h40v40H0V0zm20 20h20v20H20V20zM0 20h20v20H0V20zM20 0h20v20H20V0z\' fill=\'%23ffffff\' fill-opacity=\'0.05\' fill-rule=\'evenodd\'/%3E%3C/svg%3E")' }} />
        
        <div className="relative z-10 w-full max-w-[960px] mx-auto text-center flex flex-col items-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/10 border border-white/20 text-xs font-semibold text-white mb-8">
            <Sparkles className="w-4 h-4 text-[var(--green-accent-from)]" />
            ✦ AI Powered Fashion Intelligence
          </div>
          
          <h1 className="text-[40px] leading-[1.1] sm:text-[56px] md:text-[64px] font-extrabold text-white tracking-tight mb-6" style={{ fontFamily: 'var(--font-heading)' }}>
            Verify With Absolut <br/>
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-[var(--green-accent-from)] to-[var(--green-accent-to)] italic" style={{ fontFamily: 'var(--font-serif)' }}>Confidence.</span>
          </h1>
          
          <p className="text-[16px] sm:text-[20px] text-white/80 max-w-2xl mb-12">
            Paste any fashion product link for instant AI authenticity analysis.
          </p>
          
          <div className="w-full max-w-3xl mb-8">
             <UrlAnalyzer standalone={false} />
          </div>

          <div className="flex flex-wrap items-center justify-center gap-2 text-sm text-white/60">
            <span>Try:</span>
            <button className="px-3 py-1 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 transition-colors">amazon.in/nike-jordan</button>
            <button className="px-3 py-1 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 transition-colors">flipkart.com/gucci-bag</button>
            <button className="px-3 py-1 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 transition-colors">myntra.com/yeezy</button>
          </div>
        </div>
      </section>

      {/* 2. Tip Bar */}
      <div className="w-full bg-[#0A481C] py-3 text-center px-4">
        <p className="text-white/90 text-sm sm:text-base italic" style={{ fontFamily: 'var(--font-body)' }}>
          <span className="font-semibold text-white not-italic opacity-60 mr-2">Pro Tip:</span> 
          Type <code className="bg-black/20 px-2 py-0.5 rounded font-mono text-[var(--green-accent-from)] not-italic">veristyle.ai/ + product URL</code> to instantly unlock AI analysis.
        </p>
      </div>

      {/* 3. Stores Marquee */}
      <section className="w-full bg-white py-12 border-b border-[var(--border-subtle)] overflow-hidden">
        <div className="flex w-[200%] sm:w-[150%] lg:w-full animate-marquee items-center justify-around opacity-60 grayscale hover:grayscale-0 transition-all duration-500">
          {['Amazon', 'Flipkart', 'Myntra', 'AJIO', 'Nykaa', 'Croma', 'Meesho', 'Tata CLiQ'].map((store, i) => (
            <div key={i} className="flex items-center gap-2 font-bold text-xl text-slate-800">
               <div className="w-8 h-8 bg-gray-100 rounded-full flex items-center justify-center text-xs">{store[0]}</div>
               {store}
            </div>
          ))}
        </div>
      </section>

      {/* 4. How It Works */}
      <section className="w-full bg-[var(--page-light)] py-20 sm:py-32 px-4 sm:px-6 lg:px-8" id="how-it-works">
        <div className="max-w-7xl mx-auto space-y-16">
          <div className="text-center">
            <h2 className="text-[32px] sm:text-[42px] font-bold text-[var(--text-primary)]" style={{ fontFamily: 'var(--font-heading)' }}>
              How VeriStyle <span className="text-[var(--green-primary)] italic" style={{ fontFamily: 'var(--font-serif)' }}>Analysis Works.</span>
            </h2>
            <p className="mt-4 text-[var(--text-muted)] text-lg max-w-2xl mx-auto">
              Combining visual micro-pattern inspection with review text linguistic forensics for bulletproof authenticity scoring.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { step: 1, title: 'Find Product', desc: 'Copy the URL of any fashion item from supported stores.', icon: Search },
              { step: 2, title: 'Paste URL', desc: 'Paste the link into VeriStyle’s AI analyzer bar.', icon: ScanLine },
              { step: 3, title: 'AI Extraction', desc: 'We fetch images, price, and reviews in real-time.', icon: Brain },
              { step: 4, title: 'Get Verdict', desc: 'Receive an instant authenticity score and breakdown.', icon: CheckCircle2 }
            ].map((item, idx) => (
              <div key={idx} className="bg-white rounded-3xl p-8 border border-[var(--border-card)] shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
                <div className="w-14 h-14 rounded-2xl bg-[var(--green-primary)] flex items-center justify-center text-white mb-6">
                  <item.icon className="w-7 h-7" />
                </div>
                <div className="text-[13px] font-bold text-[var(--green-primary)] tracking-wider uppercase mb-2">Step 0{item.step}</div>
                <h3 className="text-xl font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: 'var(--font-heading)' }}>{item.title}</h3>
                <p className="text-[var(--text-muted)] text-[15px] leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 5. AI Insights Dashboard Bento */}
      <section className="w-full bg-white py-20 sm:py-32 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto space-y-16">
          <div className="text-center">
            <h2 className="text-[32px] sm:text-[42px] font-bold text-[var(--text-primary)]" style={{ fontFamily: 'var(--font-heading)' }}>
              AI Insights <span className="text-[var(--green-primary)] italic" style={{ fontFamily: 'var(--font-serif)' }}>Dashboard.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Wide Card */}
            <div className="lg:col-span-2 bg-[#F6EEFF] rounded-3xl p-8 sm:p-12 border border-[#E9D5FF] flex flex-col justify-center">
              <div className="w-12 h-12 rounded-2xl bg-purple-200 text-purple-700 flex items-center justify-center mb-6">
                <FileText className="w-6 h-6" />
              </div>
              <h3 className="text-2xl font-bold text-purple-900 mb-4" style={{ fontFamily: 'var(--font-heading)' }}>AI Review Summary</h3>
              <p className="text-purple-800/80 text-lg leading-relaxed max-w-xl">
                Our AI analyzes thousands of customer reviews in seconds, extracting genuine signals and highlighting what matters most — separating authentic buyer feedback from bot noise.
              </p>
            </div>
            
            {/* Trust Score Card */}
            <div className="bg-[#D0FAE5] rounded-3xl p-8 border border-[#A7F3D0] flex flex-col items-center justify-center text-center">
               <Shield className="w-8 h-8 text-[#059669] mb-3" />
               <h3 className="text-xl font-bold text-[#065F46] mb-2" style={{ fontFamily: 'var(--font-heading)' }}>Authenticity Score</h3>
               <div className="text-6xl font-black text-[#047857] my-4">98%</div>
               <div className="px-4 py-1.5 bg-[#059669] text-white rounded-full text-sm font-bold">VERIFIED AUTHENTIC</div>
            </div>

            {/* Fake Detection Card */}
            <div className="bg-[#FEF3C7] rounded-3xl p-8 border border-[#FDE68A]">
              <AlertTriangle className="w-8 h-8 text-[#D97706] mb-3" />
              <h3 className="text-xl font-bold text-[#92400E] mb-2" style={{ fontFamily: 'var(--font-heading)' }}>Bot Detection</h3>
              <p className="text-[#B45309] text-sm mb-6">NLP perplexity checks filter out synthetic promotion spam.</p>
              <div className="space-y-3">
                 <div className="flex justify-between text-sm font-bold text-[#78350F]"><span>Organic Language</span><span>92%</span></div>
                 <div className="w-full bg-[#FDE68A] h-2 rounded-full overflow-hidden"><div className="bg-[#D97706] h-full w-[92%]"></div></div>
              </div>
            </div>

            {/* Product Insights Card */}
            <div className="lg:col-span-2 bg-[#DBEAFE] rounded-3xl p-8 border border-[#BFDBFE]">
               <h3 className="text-xl font-bold text-[#1E3A8A] mb-4" style={{ fontFamily: 'var(--font-heading)' }}>Visual Forensics</h3>
               <div className="grid grid-cols-2 gap-4">
                 <div className="bg-white/60 p-4 rounded-2xl">
                   <p className="text-sm font-bold text-[#1E40AF]">Stitching Pitch</p>
                   <p className="text-[#3B82F6] text-sm mt-1">Conforms to factory master models.</p>
                 </div>
                 <div className="bg-white/60 p-4 rounded-2xl">
                   <p className="text-sm font-bold text-[#1E40AF]">Hardware Finish</p>
                   <p className="text-[#3B82F6] text-sm mt-1">Reflectivity matches authentic electroplating.</p>
                 </div>
               </div>
            </div>
          </div>
        </div>
      </section>

      {/* 6. AI Recommended */}
      <section className="w-full bg-[var(--page-light)] py-20 px-4 sm:px-6 lg:px-8 border-y border-[var(--border-subtle)]">
        <div className="max-w-7xl mx-auto space-y-10">
          <div className="flex items-end justify-between">
            <h2 className="text-[28px] sm:text-[36px] font-bold text-[var(--text-primary)]" style={{ fontFamily: 'var(--font-heading)' }}>
              AI <span className="text-[var(--green-primary)] italic" style={{ fontFamily: 'var(--font-serif)' }}>Recommended.</span>
            </h2>
            <button 
              onClick={onViewProducts}
              className="text-[var(--green-primary)] font-semibold hover:underline hidden sm:block"
            >
              View all →
            </button>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {PRODUCTS.slice(0, 3).map(product => (
              <ProductCard key={product.id} product={product} />
            ))}
          </div>
        </div>
      </section>

      {/* 7. Trending Products */}
      <section className="w-full bg-white py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto space-y-10">
          <div className="flex items-end justify-between">
            <h2 className="text-[28px] sm:text-[36px] font-bold text-[var(--text-primary)]" style={{ fontFamily: 'var(--font-heading)' }}>
              Trending <span className="text-[var(--green-primary)] italic" style={{ fontFamily: 'var(--font-serif)' }}>Products.</span>
            </h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {PRODUCTS.slice(3, 7).map(product => (
              <ProductCard key={product.id} product={product} />
            ))}
          </div>
        </div>
      </section>

      {/* 8. FAQ Accordion */}
      <section className="w-full bg-[var(--page-light)] py-20 sm:py-32 px-4 border-t border-[var(--border-subtle)]">
        <div className="max-w-3xl mx-auto space-y-10">
          <div className="text-center flex flex-col items-center">
            <div className="w-12 h-12 bg-gray-200 rounded-full flex items-center justify-center mb-4">
              <HelpCircle className="w-6 h-6 text-gray-500" />
            </div>
            <h2 className="text-[32px] sm:text-[42px] font-bold text-[var(--text-primary)]" style={{ fontFamily: 'var(--font-heading)' }}>
              Frequently Asked <span className="text-[var(--green-primary)] italic" style={{ fontFamily: 'var(--font-serif)' }}>Questions.</span>
            </h2>
          </div>
          <div className="space-y-4">
            {faqs.map((faq, i) => (
              <div key={i} className="bg-white border border-[var(--border-card)] rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                <button 
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full px-6 py-5 text-left flex justify-between items-center bg-white hover:bg-gray-50 transition-colors"
                >
                  <span className="font-bold text-[16px] text-[var(--text-primary)] pr-4" style={{ fontFamily: 'var(--font-heading)' }}>{faq.q}</span>
                  <ChevronDown className={`w-5 h-5 shrink-0 text-[var(--green-primary)] transition-transform ${openFaq === i ? 'rotate-180' : ''}`} />
                </button>
                {openFaq === i && (
                  <div className="px-6 pb-6 pt-2 text-[var(--text-muted)] text-[15px] leading-relaxed border-t border-gray-100 mx-6 mt-2">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

    </div>
  );
};
